### ISSUE TITLE
"Come Join The Fun" is a button that goes nowhere

### ISSUE THREAD

**Issue by kgoess** [kgoess/dance-scheduler#20]
It looks like a button, and it behaves like a button, but it doesn't do anything. Either remove it or make it do something?

<img width="677" alt="Screenshot 2024-09-19 at 8 46 39 PM" src="https://github.com/user-attachments/assets/be7453bb-297c-4ea6-b571-8b36cd61a076">

**Comment by Rahler** [comment]
Resolved by 6307df585
