### ISSUE TITLE
add a link to dance-scheduler from the main page?

### ISSUE THREAD

**Issue by kgoess** [kgoess/dance-scheduler#22]
Craig J. writes:

> how does one know get into the calendar utility? (Shoulda noticed the URL, but I didn’t.) Could it be put in the “More Tools” section under the hamburger?

He eventually found it in his browser history, but maybe we should add a link there. Unless we think it's a security problem?

**Comment by EricBlackCA** [comment]
Maybe Security Through Obscurity? There is a login required, but the site does currently allow logins with ID verified by other ID mechanisms, which we might not want to trust entirely. We would need to have a secure method of associating an outside login (via Google, etc) to the authorized BACDS person.

I'm happy with keeping it as TWK (nod to Oklahoma English) and still keeping the login requirement

Just enter:  https://bacds.org/   and add "dance-scheduler"; your web browser history will probably remember

Keeping the obscurity obscure 😁🫡😵‍💫
