### ISSUE TITLE
update info on https://bacds.org/series/virtual/oddsundays.html

### ISSUE THREAD

**Issue by starquestv** [kgoess/dance-scheduler#28]
I think it's time to call it Oddly Even Sundays in the main body (and eliminate the NOTE in the right margin)

also, since the Zoom invite is no longer shared via bacds.announce (plus the link to bacds.announce is the old mailman), I suggest we include the signup link at 

https://mailchi.mp/d5abe6c69675/zoomecd

(i.e. folks can sign up directly here - they don't have to go through Sharon, though I think she enjoys hearing from folks...)

Also, maybe include a link to the Odd Sundays Garage Band recording page https://bacds.org/odd-sundays/

**Comment by kgoess** [comment]
I made various improvements/cleanups to the page, moved a bunch of the text into the sidebar so it displays better, fixed the name as you suggest, removed a bunch of repetition, added the link to the recordings.

I left the mailchimp link off for now, if sharon enjoys it, also making the link public is kind of a policy decision that I'm not sure the two of us should be making right now.
